### ISSUE TITLE
Dependency on libwandevent

### ISSUE THREAD

**Issue by YS-L** [wanduow/libprotoident#1]
It seems that the library `libwandevent` is also a dependency during compilation; however, it is not listed on the README.

Relevant error message:

```
In file included from lpi_live.cc:53:0:
live_common.h:54:26: fatal_error: libwandevent.h: No such file or directory
#include <libevent.h>
```

**Comment by karyn** [comment]
I was able to compile and run libprotoident after installing this dependency: http://research.wand.net.nz/software/libwandevent/libwandevent-2.0.0.tar.gz

**Comment by elnappo** [comment]
I was able to compile and run libprotoident under Ubuntu 14.04 with the following commands:

```
$ sudo apt-get install libtrace3-dev libpacketdump3-dev automake libtool unp git
$ wget http://research.wand.net.nz/software/libflowmanager/libflowmanager-2.0.4.tar.gz
$ unp libflowmanager-2.0.4.tar.gz
$ cd libflowmanager-2.0.4
$ ./configure
$ make
$ sudo make install
$ cd
$ wget http://research.wand.net.nz/software/libwandevent/libwandevent-2.0.0.tar.gz
$ unp libwandevent-2.0.0.tar.gz
$ cd libwandevent-2.0.0
$ ./configure
$ make
$ sudo make install
$ cd
$ git clone https://github.com/wanduow/libprotoident.git
$ cd libprotoident
$ touch NEWS AUTHORS
$ libtoolize 
$ aclocal
$ autoconf
$ autoheader
$ automake --add-missing
$ ./configure
$ make
$ sudo make install
```

**Comment by salcock** [comment]
As of commit 179aa6b08868280978d73785c4b21f6902a57dc7, libwandevent should no longer be required by libprotoident or any of the bundled tools.

**Comment by rathnaTech** [comment]
i installed libprotodient library 
can anyone suggest the example's to use the four tools in library

**Comment by rathnaTech** [comment]
Does libprotoident support 10G interface

**Comment by rathnaTech** [comment]
using libprotoident shall we get the header details of each packet
