### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by pavel-odintsov** [wanduow/libprotoident#15]
Hello!

First of all, thanks for your great job! That's very cool to see project like this! I've some experience in hacking nDPI and I would like to contribute my help to your project too. 

I really want to use your application but actually, I could not because my application is commercial and I could not like it with GPLv2 licensed library.

Do you have some ideas for changing license to something more permissive for library code?

Thanks!

**Comment by salcock** [comment]
Thanks for your kind comments on our research!

We've had some internal discussions regarding the possibility of switching to the LGPL license for future releases of our libraries, including libprotoident and libtrace. I don't think we've reached a conclusion yet, but when people like yourself come forward and tell us that the existing license is preventing you from gaining some benefit from our research then that is definitely good encouragement for us to change licenses.

So watch this space! :)

**Comment by pavel-odintsov** [comment]
Thanks for paying attention to my case!

**Comment by salcock** [comment]
Just an update on this -- we've just released a new version of libprotoident that is now licensed under the LGPL. The same licensing change has been applied to our libraries that libprotoident depends upon (libtrace, libflowmanager, libwandio), so hopefully there shouldn't be anything stopping you from using libprotoident in your application.

**Comment by pavel-odintsov** [comment]
Great news!!!! Thank you so much :)
