### ISSUE TITLE
--with-tools build fails with libflowmanager 3.0.0

### ISSUE THREAD

**Issue by jer-gentoo** [wanduow/libprotoident#21]
configure: error: Required library libflowmanager not found; use LDFLAGS to specify library location

It isn't just the configure test that fails - the libflowmanager API has changed so much that fixing the tools isn't trivial.

Also tracked at https://bugs.gentoo.org/show_bug.cgi?id=621150 .

Kind regards,
     jer

**Comment by salcock** [comment]
Already fixed in the develop branch, so will be resolved in the next release.

Until the next official release, I'd recommend continuing to depend on the 2.0.5 release of libflowmanager. There is nothing in libflowmanager 3 that is beneficial to anyone using libprotoident 2.0.10.
