### ISSUE TITLE
Question: Can I use this project beside iptables?

### ISSUE THREAD

**Issue by GreatBahram** [wanduow/libprotoident#26]
Hi
Would it be possible to use  `libprotoident` beside `iptables`, something like `ndpi-ntefilter` project?

Thanks

**Comment by salcock** [comment]
Yes, I'm pretty sure it would be possible but would require someone to actually write the required kernel module.

Unfortunately, this isn't something that I have time to work on right now, but I'm hoping that this would be a project that someone else could pick up and provide to the community.

**Comment by GreatBahram** [comment]
@salcock 

Actually, I was looking for something that was ready right now, as you said time matters.

Thanks buddy
