### ISSUE TITLE
Can you provide the H1Z1 traces?

### ISSUE THREAD

**Issue by ChrisHffm** [wanduow/libprotoident#30]
I'm searching for the traces capture you made or someone made but I can't find anyone who did in the past, you're one of my last hope.
I tried checking on your website but I can't find anything about it :s.

Here's my email if you can send me the captures: hoffmannchris@outlook.fr

Sincerely,

**Comment by salcock** [comment]
Hello,

I've taken a look through my set of pcaps and I don't appear to have any for H1Z1.

Sorry I can't be of more assistance.
