### ISSUE TITLE
How to recompile after extending a new protocol

### ISSUE THREAD

**Issue by 15663671003** [wanduow/libprotoident#34]
I implemented a new custom tcp protocol module, how to recompile libprotoident

**Comment by salcock** [comment]
Hi,

Here are the steps you'll need to follow to add a new TCP module to libprotoident:

 * add your new source file to the `libprotoident_tcp_la_SOURCES` in `lib/tcp/Makefile.am`
 * add the registration function prototype for your module to `lib/tcp/tcp_protocols.h`
 * call your registration function in `register_tcp_protocols()` -- this function is found in `lib/proto_manager.cc`
 * add the appropriate `LPI_PROTO_XXX` for your new protocol to the `lpi_protocol_t` definition found within `lib/libprotoident.h`
 * rebuild libprotodident: `./bootstrap.sh && ./configure && make && sudo make install`

Hopefully that should help.
