### ISSUE TITLE
Can't reach site for dependencies

### ISSUE THREAD

**Issue by dandare100** [wanduow/libprotoident#46]
I cannot reach

https://research.wand.net.nz/

Is any one else having the same issue ?

![image](https://user-images.githubusercontent.com/5639208/200175249-73de2149-49eb-4e11-b1f9-1b298a0a40ef.png)

It looks like a timeout because it resolves fine

![image](https://user-images.githubusercontent.com/5639208/200175314-aed121d6-e5ca-4ac2-88f8-6d2adad1598c.png)

**Comment by dandare100** [comment]
Domain Name: wand.net.nz                                                                                                                                                                                           

Registrar URL: https://metaname.net/   
                                                                                                                                                                            **`_Updated Date: 2022-10-31T19:19:25Z_`**      
                                                                                                                                                                           Creation Date: 2002-06-12T12:00:00Z                                 
                                                                                                                                               Original Created: 2002-06-12T12:00:00Z

**Comment by salcock** [comment]
Hi there,

Unfortunately, the WAND network research group is no longer active and their infrastructure, including their websites, are no longer online.

Fortunately, you should be able to find the repositories for all of the libprotoident dependencies at https://github.com/LibtraceTeam and I'll be doing my best to try and maintain them going forward.

This will (eventually) include updating docs etc to no longer refer to WAND websites, as time permits :)

**Comment by dandare100** [comment]
Hello there.

Thank you for the reply. I appreciate it
