### ISSUE TITLE
showing error while compiling

### ISSUE THREAD

**Issue by rathnaTech** [wanduow/libprotoident#9]
Hi 
I am using libprotoident,while configuring the source code i got the below error

sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
**configure: error: Required library libtrace 3.0.7 or later not found; use LDFLAGS to specify library location**

please provide the solution to handle the issue

**Comment by elnappo** [comment]
install the requirements as pointed out in the readme.
- [libtrace](http://research.wand.net.nz/software/libtrace.php)
- [libflowmanager](http://research.wand.net.nz/software/libflowmanager.php)

close?
